In [1]:
Write a Python program that:
 Prompts the user to input a sentence.
 Counts the number of words, characters (excluding spaces), and vowels in the sentence.
 Prints the results in a formatted manner.

 Example:
 Enter a sentence: Data Science is awesome!
 Number of words: 4
 Number of characters (excluding spaces): 19
 Number of vowels: 9

SyntaxError: invalid syntax (2386467607.py, line 1)

In [ ]:
s = input('Enter a sentence: ')

num_word = len(s.split())
num_char = len(s)
num_vowel = sum(1 for char in s.lower() if char in 'aeiou')


print(f"word: ", num_word)
print(f"char: ", num_char) 
print("Number of vowels:", num_vowel)

In [ ]:
def factorial(n):
    # Check if input is a non-negative integer
    if not isinstance(n, int) or n < 0: 
        raise ValueError("Please enter a non-negative integer")
    
    # Calculate factorial
    result = 1
    for i in range(1, n + 1): 
        result *= i 
    return result

# Testing
try: 
    print('Factorial of 5:', factorial(5))  # Valid input
    print('Factorial of -3:', factorial(-3))  # Invalid input
except ValueError as e: 
    print("Error:", e)

In [ ]:
Perform the following tasks:
 Create a new list containing the squares of all even numbers from the original list using a list
 comprehension. (5 Marks)
 Sort the original list in descending order without using the built-in 

(b) Dictionary Operations (10 Marks)
 You have a dictionary representing employees and their departments:
 employees = {
 "E001": "HR",
 "E002": "IT",
 "E003": "Finance",
 "E004": "IT",
 "E005": "HR",
 "E006": "Marketing",
 "E007": "Finance",
 sort() method. 

In [ ]:
numbers = [3, 7, 2, 9, 12, 15, 8, 6] 

for i in numbers: 
    if i % 2 == 0: 
        print(i**2)

In [ ]:
numbers = [3, 7, 2, 9, 12, 15, 8, 6]

def bubbleSort(numbers): 
    n = len(numbers)
    # Outer loop for passes
    for i in range(n):
        # Inner loop for comparisons
        for j in range(0, n - i - 1): 
            # Compare adjacent elements
            if numbers[j] < numbers[j + 1]:
                # Swap if in wrong order
                numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]
    return numbers

# Call the function and print results
result = bubbleSort(numbers)
print("Numbers sorted in descending order:", result)

In [3]:
numbers = [3, 7, 2, 9, 12, 15, 8, 6]

def bublesort(numbers): 
    n = len(numbers)

    for i in range(n): 
        for j in range(0, n - i - 1): 
            if numbers[j] < numbers[j + 1]: 
                temp = numbers[j]
                numbers[j] = numbers[j + 1]
                numbers[j + 1] = temp
        return numbers

# Call the function and print results
result = bublesort(numbers)
print("Numbers sorted in descending order:", result)

Numbers sorted in descending order: [7, 3, 9, 12, 15, 8, 6, 2]


In [8]:
# (b) Dictionary Operations (10 Marks)
# You have a dictionary representing employees and their departments:

employees = {
     "E001": "HR",
     "E002": "IT",
     "E003": "Finance",
     "E004": "IT",
     "E005": "HR",
     "E006": "Marketing",
     "E007": "Finance",
     "E008": "IT"
 }

new_dictionary = {}

for emp_id, dept in employees.items(): 
    if dept not in new_dictionary: 
        new_dictionary[dept] = []
    new_dictionary[dept].append(emp_id)
print('New Dictionary is:', new_dictionary)


# maximum department finding.
# max_dept = max(new_dictionary, key=lambda k: new_dictionary[k])
max_dept = max(new_dictionary, key=lambda k: len(new_dictionary[k]))
print('Maximum department is: ', max_dept)

New Dictionary is: {'HR': ['E001', 'E005'], 'IT': ['E002', 'E004', 'E008'], 'Finance': ['E003', 'E007'], 'Marketing': ['E006']}
Maximum department is:  IT


# Question 3: NumPy Array Operations.

# (a) Array Creation and Statistical Analysis (10 Marks)
# Create a NumPy array 
- data of 100 random integers between 50 and 150. (2 Marks)
- Reshape the array into a (20, 5) matrix. (2 Marks)
- Calculate the following statistics for the entire dataset:
     - Mean
     - Median
     - Standard Deviation
     - Variance (4 Marks)
- Find the maximum value in each column and store the results in a one-dimensional array. (2 Marks)

In [11]:
import numpy as np 
arrary = np.random.randint(50, 150, size=(20, 5))
print(arrary)

[[104 118  51  63  54]
 [111 136  83 132 112]
 [ 60  54 103  99 147]
 [106  72 129 132  99]
 [ 76 149 128  53 143]
 [ 93 111 133  84 141]
 [106 109  73  52  55]
 [145 101 124  85 135]
 [136 124  61 146  77]
 [ 78  59 130  59  57]
 [109  71 121  57  63]
 [ 69  63 131  54 121]
 [ 87  86 127 147  74]
 [130  54 137 122 112]
 [147 135 129 128 144]
 [104 103  54 149 124]
 [129 100 122  84 130]
 [101 129  56  98 103]
 [ 57  66 145  51 121]
 [120  52 145  89 117]]


In [12]:
mean_value = arrary.mean()
median_value = np.median(arrary)
mode_value = arrary.std()
varience_value = arrary.var()
print(varience_value)

1001.7275


## (b) Logical Indexing and Filtering (5 Marks)

In [20]:
#arr = np.array[10,20,30,40,50,60,90,110,200,300,500,641]

mask = arrary <= 100
filter_values = arrary[mask]
percentage = (len(filter_values / arrary.size)) * 100

print("Filtered values <= 100:", filter_values)
print(percentage)

Filtered values <= 100: [ 51  63  54  83  60  54  99  72  99  76  53  93  84  73  52  55  85  61
  77  78  59  59  57  71  57  63  69  63  54  87  86  74  54  54 100  84
  56  98  57  66  51  52  89]
4300


In [22]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 

In [23]:
df = pd.read_csv('customer_data.csv')
df.head()

CustomerID     Name  Age  Gender  AnnualIncome  SpendingScore
0           1    Alice   25  Female         50000             70
1           2      Bob   34    Male         60000             65
2           3  Charlie   29    Male         52000             50
3           4    David   42    Male         72000             40
4           5      Eva   37  Female         58000             85

In [24]:
df.describe() 

CustomerID        Age  AnnualIncome  SpendingScore
count    10.00000  10.000000     10.000000      10.000000
mean      5.50000  38.800000  63800.000000      57.500000
std       3.02765  12.236557  13011.106367      21.889876
min       1.00000  25.000000  50000.000000      20.000000
25%       3.25000  29.500000  55000.000000      42.500000
50%       5.50000  35.500000  59000.000000      62.500000
75%       7.75000  46.500000  70000.000000      73.750000
max      10.00000  62.000000  90000.000000      85.000000

In [ ]:
# Display the basic statistics of numerical columns using .describe() 

